[package]
name = "lsp-ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
lsp-server = "0.7.4"
lsp-types = "0.94.1"
once_cell = "1.18.0"
parking_lot = "0.12.1"
ropey = "1.6.1"
serde = "1.0.190"
serde_json = "1.0.108"
# candle-core = { git = "https://github.com/huggingface/candle/", version = "0.3.1", features = ["accelerate"] }
# candle-nn = { git = "https://github.com/huggingface/candle/", version = "0.3.1", features = ["accelerate"] }
# candle-transformers = { git = "https://github.com/huggingface/candle/", version = "0.3.1", features = ["accelerate"] }
candle-core = { path = "../candle/candle-core", version = "0.3.1", features = ["accelerate"] }
candle-nn = { path = "../candle/candle-nn", version = "0.3.1", features = ["accelerate"] }
candle-transformers = { path = "../candle/candle-transformers", version = "0.3.1", features = ["accelerate"] }
hf-hub = { git = "https://github.com/huggingface/hf-hub", version = "0.3.2" }
rand = "0.8.5"
tokenizers = "0.14.1"

